#!/usr/bin/env node
const npmPath = require('npm-path');
const Abigail = require('./').Abigail;

// update process.env
npmPath();

/*
* abigail lifecycle (in serial)
*   initialized
*   parse
*   attach-plugins
*   (unless task) -> output logo && exit 1
*   launch
*     task-start (in parallel)
*       script-start
*       script-end
*       script-error
*     task-end
*   detach-plugins
*   exit
*   (all expection) -> output trace && exit 1
*/

const abigail = new Abigail().initialize(process.argv.slice(2));
abigail.emit('initialized')
.then(() => abigail.emit('parse', abigail.props.globs, abigail.props.json.data.scripts))
.then(() => abigail.emit('attach-plugins'))
.then(() => abigail.emit('launch', abigail.props.task))
.then(() => {
  if (abigail.listeners('exit').length) {
    return abigail.emit('detach-plugins')
    .then(() => abigail.emit('exit'));
  }

  return process.once('SIGINT', () => {
    try {
      abigail.props.plugins.log.abort();
    } catch (e) {
      // ignore
    }

    abigail.emit('detach-plugins')
    .then(() => abigail.emit('exit'));
  });
})
.catch((reason) => {
  console.trace(reason.message); // eslint-disable-line no-console
  process.exit(1);
});
